### ISSUE TITLE
brak linków w javadocach

### ISSUE THREAD

**Issue by koral--** [DroidsOnRoids/jspoon#12]
Np. https://static.javadoc.io/pl.droidsonroids/jspoon/1.0.0/pl/droidsonroids/jspoon/annotation/Selector.html#NO_VALUE
vs 
https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.7/pl/droidsonroids/gif/GifError.html#description

Klasy z JDK powinny linkować do javadoców na stronce Oracle.

Tak to jest zrobione w projekcie androidowym:
https://github.com/koral--/android-gif-drawable/blob/master/android-gif-drawable/gradle-mvn-push.gradle#L100

**Comment by burnoo** [comment]
#8

**Comment by burnoo** [comment]
Spróbowałem nadpisać task `javadoc` w #13

**Comment by koral--** [comment]
Hint: jeśli w commit message'u napiszesz "fixes #12" to issue sam się zamknie po zmergowaniu.
