### ISSUE TITLE
how to parse img tag without id 

### ISSUE THREAD

**Issue by s3hengwu** [DroidsOnRoids/jspoon#15]
example:

htmlContent : img src = "http://xxxxx"

your example:

htmlContent : img src = "http://xxxxx" id="image1"

**Comment by burnoo** [comment]
You should look for the image using [CSS Selectors](https://www.w3schools.com/cssref/css_selectors.asp) and find characteristic container.

Example
HTML:
```html
...
<div id="image-container">
  <img src ="img.jpg" />
</div>
...
```
jspoon:
```java
class Image {
    @Selector(value="#image-container > img", attr="src") String imageUrl;
}
```

Another solution - when you really can't find any specific container - is to use `index`.
Assuming that your image appears as third in HTML:
```java
class Image {
    @Selector(value="img", attr="src", index="2") String imageUrl;
}
```

**Comment by koral--** [comment]
@s3hengwu you haven't posted entire HTML so there are many answers depends on exact body.
Some other options in addtion to @burnoo's answer:

- if there is only one image you can just use `@Selector(value="img", attr="src")`
- if src URL follows some pattern you can use regular expression e.g. for for HTTP(S) URLs with host `example.com` ending with `jpg`: `@Selector(value="img[src~=https?://example.com/.*jpg]", attr="src")`

**Comment by s3hengwu** [comment]
thank you for your help
