### ISSUE TITLE
dynamically page content

### ISSUE THREAD

**Issue by Onregs** [DroidsOnRoids/jspoon#16]
Hi, I use that library to get content from pages, it's quite easy for static pages. Now I want to use it to get content from statically pages. So I'm able to get a text, images etc. from a page, but then I need to put images in right place in the text, so how can I do it?

**Comment by burnoo** [comment]
If I understand you, you want to edit downloaded HTML, right?
In this case you should use [Jsoup](https://jsoup.org/cookbook/modifying-data/set-attributes)

Jspoon is only one way tool - it parse HTML into Java.
