### ISSUE TITLE
Consider moving the examples module in a separate repo

### ISSUE THREAD

**Issue by devcsrj** [DroidsOnRoids/jspoon#22]
Hi again! 

When building the whole project in this repo with `./gradlew build`, the process fails on my machine because I don't have android sdk installed, which the `android-example` needs. So when I wrote my recent PRs, I had to temporarily remove that module through the `settings.gradle`.

Might be better if they're promoted in a separate repo like `jspoon-examples`. Not sure if this is worth the change for you guys, so I just opened an issue.

**Comment by koral--** [comment]
> the process fails on my machine because I don't have android sdk installed

I would rather solve that. Either by checking for SDK and ignoring that module it SDK is not installed or by trying to install it.

**Comment by burnoo** [comment]
Fixed in #23
