### ISSUE TITLE
How to get text of current Element

### ISSUE THREAD

**Issue by jordyamc** [DroidsOnRoids/jspoon#26]
I have a Object that creates a list of Objects, i pass de `<li>` selector to the list, but how do i get the ownText of the Current element?

```
class A{
     @Selector("li")
     List<B> objects;
     
     class B{
          //How to get the ownText of the parent li?
          String text;
     }
}
```

**Comment by jordyamc** [comment]
Is it correct to make `@Selector("li")`?

**Comment by burnoo** [comment]
You can use `@Selector(":root")`

**Comment by jordyamc** [comment]
Thanks
