### ISSUE TITLE
Add support for explicit default contructor and non annotated variables

### ISSUE THREAD

**Issue by jordyamc** [DroidsOnRoids/jspoon#27]
I want no make a multipurpose Object to use Jspoon and Room but if i add a constructor to the class the library throws noDefaultConstructorFoundException like this

```Java
@Entity
class A{
     @PrimaryKey
     int key; //For Room
     String some; //For Room
     String other; //For Room
     @Selector("css")
     String web; //For Room and Jspoon
     
     //Constructor for Room
     A(int key, int String some, String other, String web){
          //Set variables code
     }

     //Constructor for Jspoon
     @Ignore //Room annotation to ignore constructor
     A(String web){
          //Web set
     }
}
```

**Comment by jordyamc** [comment]
Up until now i have to Split the Room part and move the Jspoon to a inner Class (wich i can use with Room using @Embeded annotation) but for  less complex structure i would like to use it like the example

**Comment by jordyamc** [comment]
Also i need the constructor in Jspoon part to add/remove/modify the String or something similar

**Comment by burnoo** [comment]
How about adding a constructor without parameters?
```java
@Ignore //Room annotation to ignore constructor
A() {
}
```

**Comment by jordyamc** [comment]
Mmm.. thats a solution to the Object, but in case a wanted to add/delete/modify the value on the object creation?

**Comment by cr3ativ3** [comment]
Since Jspoon would not know what to set for the constructor argument you would have nothing to add/delete/modify. Not even a String can be set as it parses/selects nodes only after target object instantiation. I don't think its possible (or wise) to allow it to somehow use other than no-arg constructor. Although the only option would be to set all arguments to null, but that could lead to many NullPointerExceptions out of nowhere. 

However I assume you first create an instance with Room then use Jspoon adapter to set other values. In that case I also think support for populating instances not only classes would be a welcome feature.

Example:
```
MyPojo pojoInstance = ... // resolve entity from room or something
pojoInstance = jspoon.adapter(pojoInstance).fromHtml(html);
```

**Comment by jordyamc** [comment]
I'm currently using a work-around, i create an Object containing all variables, then i add a inner static class containing Selector only variables and make jspoon populate it, then make my main object be populated by the inner class, then my main object can used by Room and Jspoon

**Comment by cr3ativ3** [comment]
@jordyamc could you create a small sample project to illustrate your use case? I think it could be solved by allowing loading of created instances, but at this point I'm only guessing how you're using Room.

**Comment by jordyamc** [comment]
It's very simple
Class for Room and Jspoon:
```Java
@Entity
public class Test {
    @PrimaryKey
    public int key;
    public String t1;
    public String t2;
    public String t3;

    public Test(int key, String t1, String t2, String t3) {
        this.key = key;
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
    }

    @Ignore
    public Test(Web web){
        this.key=Integer.parseInt(web.key);
        this.t1=web.t1;
        this.t2=web.t2;
        this.t3=web.t3;
    }

    public static class Web{
        @Selector("p.key")
        public String key;
        @Selector("p.t1")
        public String t1;
        @Selector("p.t2")
        public String t2;
        @Selector("p.t3")
        public String t3;
    }
}
```
And for creation:
```Java
Test test=new Test(Jspoon.create().adapter(Test.Web.class).fromHtml("html"));
```

Now my class `Test` can be used with Room to save/get from database, and also be created using Jspoon

**Comment by cr3ativ3** [comment]
hmm. I don't see why you can't  define it like this
```
@Entity
public class Test {
    @PrimaryKey
    @Selector("p.key")
    public int key;
    @Selector("p.t1")
    public String t1;
    @Selector("p.t2")
    public String t2;
    @Selector("p.t3")
    public String t3;

    public Test(int key, String t1, String t2, String t3) {
        this.key = key;
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
    }

    @Ignore
    public Test(){ }
}
```
And use it like:
```
Test test = Jspoon.create().adapter(Test.class).fromHtml("html");
db.getDao().save(test);
```

**Comment by cr3ativ3** [comment]
@jordyamc What do you think of the suggested solution above, would that work?

**Comment by jordyamc** [comment]
Thats in case i wanted to do it directly, but if i wanted to modify de data on creation.....

Like.... Modifying an extracted link changing http to https and so, in your example i would have to do it post creation of the object

**Comment by cr3ativ3** [comment]
@jordyamc yes, but thats a very particular/custom use case. I don't know if that requires any support on the library side. For example you want to timestamp the html data, you can just:
```
Test test = Jspoon.create().adapter(Test.class).fromHtml("html");
test.setSnapshotFrom(new Date());
db.getDao().save(test);
```

**Comment by jordyamc** [comment]
Well i think i will do it like that
