### ISSUE TITLE
Support for optional field selector

### ISSUE THREAD

**Issue by cr3ativ3** [DroidsOnRoids/jspoon#29]
Support for marking a field as being "optional". Either through `Selector(optional = true)` attribute or a seperate `@Optional` annotation. So that in some cases when field's value cannot be resolved it could be left unset (_null_) while adapter continues field mapping without throwing an exception.

**Comment by devcsrj** [comment]
[nit] I want this too! Although instead of optional, how about `@Nullable` and `nullable = true`.. Just to keep in-sync with the `javax.annotation.Nullable` and `javax.persistence.Column#nullable`. Because of Java 8, I always associate _optional_ with the `java.util.Optional` object.
