### ISSUE TITLE
Selector support for custom "converters"

### ISSUE THREAD

**Issue by cr3ativ3** [DroidsOnRoids/jspoon#30]
I was planning on implementing something similar on top of Jsoup when I stumbled upon this gem of a library. It's really great, but I find myself lacking a few key features to be able to fully use it in my projects. 

One of the features is specifying a custom converter (can be called converter /resolver /etc.) to resolve field value from HTML String (other two are described as #28 and #29). I could fork this and implement my self, but I think they would be useful for others and it would be great if they could make it to the main project.

There are cases when one would want a more complex parsing than could be accomplished with a String regex. For example to parse:
`<p id="today-weather">Today is Saturday. Weather is sunny</p>`

If you want to parse this into custom enum fields `DayOfWeek ` and  `Weather` it woul be great to have custom converters to do it if specified like:

```
public class WebPage {

    @Selector(value="#today-weather", converter=DayConverter.class)
    DayOfWeek dayOfWeek;

    @Selector(value="#today-weather", converter=WeatherConverter.class)
    DayOfWeek dayOfWeek;
}
```

where DayConverter must implement some

```
abstract class ElementConverter<T> {

    T resolve( Field field, Selector selector, Element node);
}
```

currently the only solution is to map to Element and have a separate method that _must_ be called post html resolve to populate such fields like:
```
public class WebPage {

    @Selector(value="#today-weather")
    Element todayWeather

    DayOfWeek dayOfWeek;

    DayOfWeek dayOfWeek;

    ...
    void postResolve(){

        this.dayOfWeek = new DayConverter().resolve(todayWeather);
        ...
    }
}
```

**Comment by burnoo** [comment]
I think this is a great idea!  (#28 and #29 as well)

> I could fork this and implement my self, but I think they would be useful for others and it would be great if they could make it to the main project.

I encourage you to open a pull request - we will review it and release the new version ;)

**Comment by cr3ativ3** [comment]
Huge thabks for this addition. I'm very sorry I couldn't get on this for the past few weeks. I will tryto look throu the new changes tonight.
One thing tonote streight away, it would be very useful to have access to the Field in the cinvert method as well. In case one would want to scan for other Annotations ir do something based on Field's type

**Comment by cr3ativ3** [comment]
I know I myself suggested the name 'converter' but thinking more about this  - a converter implies it's  something that _convert_ the String value already _parsed_ from the Element node. Since this accepts the whole Element I think a 'parser' would be more appropriate name. What do you guys think?

**Comment by burnoo** [comment]
It would be a big change, so I prefer to don't change a name.
