### ISSUE TITLE
Get child elements

### ISSUE THREAD

**Issue by shtil** [DroidsOnRoids/jspoon#48]
Hi
How I can get child elements?
In jsoup I use  links.get(i).**children()**
For example:
 
`<div class="abc">`
`    <div class ="a">A</div>`
`    <div>A</div>`
`    <div class ="b">B</div>`
`</div>`

I need get 
`@Selector("??????")`
`List<Div> divsList;`

Thank you

**Comment by burnoo** [comment]
Children of `.abc`:
`@Selector(".abc > *")`
