### ISSUE TITLE
Jsoup bug on Android <6.0

### ISSUE THREAD

**Issue by jonbulica99** [DroidsOnRoids/jspoon#52]
Please refer to this issue first: https://github.com/jhy/jsoup/issues/992

The "solution" presented there says we should downgrade to Jsoup `1.10.3`, however since Jsoup isn't a direct dependency of my project, but rather of Jspoon I cannot do that. This affects 35% of my userbase and I cannot just ignore that. Further assistance is appreciated.

Edit: if there is some gradle wizardry to override dependencies for external libraries I'd like to know :)

**Comment by jonbulica99** [comment]
Ok after some googling I found the solution. In gradle you can explicitly specify which version of a transitive dependency shall be compiled. Define this in your app's `build.gradle`:
```
android {
    configurations.all {
        resolutionStrategy.force 'org.jsoup:jsoup:1.10.3'
    }
}
```
If you have multiple dependencies or just want to go fancy with it, you can apply some black magic to gradle. Firstly define an array with all your dependencies:
```
def versionOverrides = [
        "org.jsoup:jsoup": "1.10.3",
        "com.google:support": "27.1.0"
        [...]
]
```
then insert this in your `configurations.all` clause:
```
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def overrideVersion = versionOverrides[details.requested.group + ":" + details.requested.name]
            if (overrideVersion != null && details.requested.version != overrideVersion) {
                logger.info "Overriding dependency ${details.requested.group}:${details.requested.name} version ${details.requested.version} --> $overrideVersion"
                details.useVersion overrideVersion
            }
        }
```
I take no credit for any of the gradle scription mentioned here. :)

**Comment by cr3ativ3** [comment]
@jonbulica99 or less invasive and more straightforward solution - in `build.gradle` dependencies you can just exclude jsoup's transitive dependency and add your own to the compile classpath

```
dependencies {

  compile('pl.droidsonroids:jspoon:1.2.2') {
     exclude group: 'org.jsoup', module: 'jsoup'
  }
  compile 'org.jsoup:jsoup:1.10.3'

}
```

**Comment by jonbulica99** [comment]
thanks @cr3ativ3, this seems way cleaner and less hacky.
