### ISSUE TITLE
If a rejex does not match, return value instead default value

### ISSUE THREAD

**Issue by MiguelAngelLV** [DroidsOnRoids/jspoon#77]
**Describe the bug**

If you use a regex for a value and the rejex does not match, return the original value instead the default value:

You can see this in the code

https://github.com/DroidsOnRoids/jspoon/blob/master/jspoon/src/main/java/pl/droidsonroids/jspoon/HtmlField.java#L137

**Expected behavior**
If regex don't match, return default value

**Additional context**
Maybe, for backward compatibility, add "defaultRegex" parameter for example.

**Comment by koral--** [comment]
Could you create a PR for that?

**Comment by MiguelAngelLV** [comment]
I can try.

What do you prefer? default or defaultRegex?

For me, is more clean only default-

**Comment by koral--** [comment]
I think the default value is enough.

**Comment by MiguelAngelLV** [comment]
You have a PR

**Comment by koral--** [comment]
https://github.com/DroidsOnRoids/jspoon/pull/78 merged.
